// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3244.Jupiter2019.commands;

import org.usfirst.frc3244.Jupiter2019.Robot;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.PIDCommand;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import oi.limelightvision.limelight.frc.LimeLight;

/**
 *
 */
public class Drive_LimeLight_PIDCommand extends PIDCommand {

	private static final boolean debug = false;
	
	private static final double kP = 0.03;
	private static final double kI = 0.00;
	private static final double kD = .20;//0.4;
	
    private boolean rotateToAngle;
	private double rotateToAngleRate;
	static final double kToleranceDegrees = 2.0f;
	
	
	private double m_x;
    private double m_y;
    private double m_currentRotationRate;
    private double m_setpoint;
    
    private int m_pipeline;
    //Timer m_timer = new Timer();
	
	
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public Drive_LimeLight_PIDCommand(int pipeline) {
   
        super("turnController", kP, kI, kD, 0.02);
        getPIDController().setInputRange(-30.0f,  30.0f);
        getPIDController().setOutputRange(-0.25, 0.25);
        getPIDController().setAbsoluteTolerance(kToleranceDegrees);
        getPIDController().setContinuous(true);
 
        requires(Robot.driveTrain_1519_MM);
        m_pipeline = pipeline;
        m_setpoint = 0;
        
    }

    protected double returnPIDInput() {

    LimeLight limelight = Robot.oi.get_my_LimeLight();
    double rotation = 0.0;
    if(limelight.getIsTargetFound()){
      if(debug){
        SmartDashboard.putBoolean("Target Found", true);
      }
     
      rotation = limelight.getdegRotationToTarget();
    }else{
        rotation = 0.0;
    }
        
    	return rotation;
        //return RobotMap.ahrs.getAngle();
      
    }

    protected void usePIDOutput(double output) {
      
    	rotateToAngleRate = output;
        
    }

    // Called just before this Command runs the first time
    protected void initialize() {

        Robot.oi.get_my_LimeLight().setPipeline(m_pipeline);
    	
    	if(debug){
    		System.out.println("tCurrent setpoint: " + m_setpoint);
    	}
        getPIDController().setSetpoint(m_setpoint);
        rotateToAngle = true;
    	Robot.driveTrain_1519_MM.zeroDistanceTraveled();
    	//m_timer.reset();
    	//m_timer.start();    	
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	m_y = Robot.oi.driveY();
    	getPIDController().enable();    
        m_currentRotationRate = rotateToAngleRate;

        if(debug){
            System.out.println("m_currentRotationRate: " + m_currentRotationRate);
        }

        
        m_y = Robot.oi.driveY() * 0.6;
        Robot.driveTrain_1519_MM.driveTeleop(m_y, m_currentRotationRate, true, false);
  
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	getPIDController().disable();
    	// note:  it is important to call mecanumDriveCartesian here, rather than mecanumDriveAutonomous,
    	// to ensure that "heading preservation" isn't activated for the last instruction
    	//Robot.driveTrain_1519_MM.driveAutoInTeleopFinished();
    	//Robot.driveTrain_1519_MM.driveCartesian(0.0, 0.0);
        //SmartDashboard.putNumber("Time", m_timer.get());
        Robot.driveTrain_1519_MM.driveTeleop(0.0,0.0);
        Robot.rgb_LEDs.set_myRGB("off");
        Robot.oi.get_my_LimeLight().setPipeline(0);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	end();
    }
}
