// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3244.Jupiter2019.commands;

import org.usfirst.frc3244.Jupiter2019.Robot;

import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.command.ConditionalCommand;


/**
 *
 */
public class DriveToggleShifter extends ConditionalCommand {

    public DriveToggleShifter() {
      //super(new Auto_12_3_1_Deliver_Left_Scale_90_To_Plate(), new Auto_00_Reach_BaseLine());
      //super(new Auto_12_3_1_Deliver_Left_Scale_45_To_Plate(), new Auto_00_Reach_BaseLine());
      super(new Drive_ShiftHigh(), new Drive_ShiftLow());
    }

    @Override
    protected boolean condition(){
    	if(Robot.driveTrain_1519_MM.my_GetIsCurrentGearHigh()){
    		return false;
        }else {
        	return true;
        }
    }
}
