// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3244.Jupiter2019.commands;
import edu.wpi.first.wpilibj.command.InstantCommand;
import org.usfirst.frc3244.Jupiter2019.Robot;

/**
 *
 */
public class Hatch_Slide extends InstantCommand {

    private boolean m_extend;
 
    public Hatch_Slide(boolean extend) {
        m_extend = extend;
        requires(Robot.hatch);
    }

    // Called once when this command runs
    @Override
    protected void initialize() {
        Robot.hatch.my_Hatch_Extend(m_extend);
    }

}
